---
swagger: "2.0"
info:
  description: "A sample API that uses a petstore as an example to demonstrate features\
    \ in the swagger-2.0 specification"
  version: "1.0.1"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Swagger API Team"
  license:
    name: "MIT"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /petz:
    get:
      description: "Returns all pets from the system that the user has access to"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "A list of pets!"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Pet"
definitions:
  Pet:
    type: "object"
    required:
    - "id"
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "hejsan "
      tag:
        type: "string"
        example: "my tag\nhas many\nlines"
