/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.Pet
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DefaultApi {

  /**
   * Returns all pets from the system that the user has access to
   * 
   * Expected answers:
   *   code 200 : Seq[Pet] (A list of pets!)
   */
  def petzGet(): ApiRequest[Seq[Pet]] =
    ApiRequest[Seq[Pet]](ApiMethods.GET, "https://localhost", "/petz", "application/json")
      .withSuccessResponse[Seq[Pet]](200)
      

}

